#   help:http://albert-oma.blogspot.tw/2012/04/cunit.html
	#error : dereferencing pointer to incomplete type 「WINDOW {aka struct _win_st}」=> -DNCURSES_OPAQUE=0
	#grep "struct _win_st" /usr/include/ -R
	#	in /usr/include/ncurses.h line 418: #if !NCURSES_OPAQUE
	#	in /usr/include/ncurses.h line 109:
											#ifndef NCURSES_INTERNALS
											#define NCURSES_OPAQUE 1
											#endif => -DNCURSES_INTERNALS
all:
	gcc -Wall server.c -g -o server -pthread #-lsocket -lnsl
	gcc -Wall clt.c -g -o client -pthread -lcurses -DNCURSES_INTERNALS -DNCURSES_OPAQUE=0 #-lsocket -lnsl
clean:
	rm -f server client
